backend:
  name: git-gateway
  branch: main
site_url: http://bolokoz.netlify.app
display_url: http://bolokoz.netlify.app
media_folder: assets/images
public_folder: assets/images
local_backend: true
media_library:
  name: cloudinary
  config:
    cloud_name: boloko
    api_key: 546499289928484
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - {
              label: Site Name,
              name: sitename,
              widget: string,
              hint: 'This is used for the site title',
            }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern:
                [
                  '^[a-z]{2}([-])?([A-Za-z]{2})?$',
                  'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")',
                ],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'areas_dev'
    label: 'areas/dev'
    folder: 'content/areas/dev'
    create: true
    format: 'frontmatter'
    slug: '{{fields.createdAt}}-{{slug}}'
    editor:
      preview: true
    fields:
      - {
          label: 'Created Date',
          name: 'createdAt',
          widget: 'datetime',
          format: 'YYYY-MM-DD',
          date_format: 'YYYY-MM-DD',
          time_format: false,
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - {
          label: 'Cover Image',
          name: 'cover',
          widget: 'image',
          required: false,
          allow_multiple: false,
        }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
      - { label: 'Tags', name: 'tags', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - name: 'areas_eng'
    label: 'areas/eng'
    folder: 'content/areas/engineering'
    create: true
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    format: 'frontmatter'
    slug: ''
    editor:
      preview: true
    fields:
      - {
          label: 'Created Date',
          name: 'createdAt',
          widget: 'datetime',
          format: 'YYYY-MM-DD',
          date_format: 'YYYY-MM-DD',
          time_format: false,
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - {
          label: 'Cover Image',
          name: 'cover',
          widget: 'image',
          required: false,
          allow_multiple: false,
        }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
      - { label: 'Tags', name: 'tags', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - name: 'foodrating'
    label: 'Food Rating'
    label_singular: 'FoodRating'
    folder: 'content/resources/foodrating'
    create: true
    format: 'frontmatter'
    slug: '{{fields.title}}-{{fields.restaurante.name}}'
    fields:
      - { label: 'Nome do prato', name: 'title', widget: 'string', required: true }
      - label: 'Nome do restaurante'
        name: 'restaurante'
        widget: 'string'
      - { label: 'Location', name: 'location', widget: 'map' }
      - {
          label: 'Categoria',
          name: 'category',
          widget: 'select',
          options:
            [
              { label: 'Lanche', value: 'lanche' },
              { label: 'Doce', value: 'doce' },
              { label: 'marmita', value: 'marmita' },
              { label: 'carnes', value: 'carnes' },
              { label: 'pizza', value: 'pizza' },
              { label: 'peixes', value: 'peixes' },
              { label: 'parmegiana', value: 'parmegiana' },
              { label: 'sushi', value: 'sushi' },
              { label: 'self-service', value: 'self-service' },
              { label: 'Café', value: 'café' },
              { label: 'Paçoca', value: 'paçoca' },
            ],
        }
      - label: 'Valor'
        name: 'valor'
        widget: 'number'
        value_type: 'int'
        max: 3000
        min: 1
        step: 1
      - label: 'Nota Sentimental'
        name: 'nota_sentimental'
        widget: 'number'
        value_type: 'int'
        max: 3
        min: 1
        step: 1
      - label: 'Nota tecnica'
        name: 'nota_tecnica'
        value_type: 'int'
        step: 1
        widget: 'number'
        max: 3
        min: 1
      - {
          label: 'Observação sentimental',
          name: 'obs_sentimental',
          widget: 'string',
          required: false,
        }
      - { label: 'Data da refeição', name: 'date', widget: 'date', format: 'YYYY-MM-DD' }
      - { label: 'Image', name: 'image', widget: 'image', required: false, allow_multiple: false }
      - { label: 'Delivery', name: 'delivery', widget: 'boolean', default: 'false' }
      - {
          label: 'Periodo',
          name: 'periodo',
          widget: 'select',
          options:
            [
              { label: 'café', value: 'café' },
              { label: 'almoço', value: 'almoço' },
              { label: 'janta', value: 'janta' },
            ],
        }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
